version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - dma-network

  api:
    image: peaceoutommy/dma-api:${API_VERSION:-main}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - STIPE_PUB_KEY=${STIPE_PUB_KEY}
      - STRIPE_PRIV_KEY=${STRIPE_PRIV_KEY}
      - STRIPE_WEBHOOK_PRIV=${STRIPE_WEBHOOK_PRIV}
    ports:
      - "8080:8080"
    networks:
      - dma-network

  client:
    image: peaceoutommy/dma-client:${CLIENT_VERSION:-main}
    depends_on:
      - api
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - dma-network

volumes:
  mysql-data:

networks:
  dma-network:
    driver: bridge